# backend/main.py
import os
import shutil
from typing import List

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ---------- CONFIG ----------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FILES_DIR = os.path.join(BASE_DIR, "boardwalk_files")
os.makedirs(FILES_DIR, exist_ok=True)

# ---------- APP ----------
app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------- MODELS ----------
class Message(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[Message]

class ChatResponse(BaseModel):
    reply: str

class ScaffoldRequest(BaseModel):
    stack: str
    name: str

class ScaffoldResponse(BaseModel):
    message: str
    path: str

class DbSchemaRequest(BaseModel):
    name: str
    schema: str

class DbSchemaResponse(BaseModel):
    message: str
    path: str

class R2Request(BaseModel):
    bucket_name: str

class R2Response(BaseModel):
    message: str
    path: str

class ApiGenRequest(BaseModel):
    project: str
    spec: str

class ApiGenResponse(BaseModel):
    message: str
    path: str

# ---------- HELPERS ----------
def safe_name(name: str) -> str:
    return name.replace("..", "_").strip().replace(" ", "-")

# ---------- SCAFFOLD FULL-STACK PROJECT ----------
def scaffold_project(stack: str, name: str) -> str:
    sname = safe_name(name)
    base = os.path.join(FILES_DIR, sname)

    if os.path.exists(base):
        shutil.rmtree(base)
    os.makedirs(base, exist_ok=True)

    with open(os.path.join(base, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# {sname}\n\nGenerated by Boardwalk AI App Builder.\n")

    if stack == "react-node":
        backend_dir = os.path.join(base, "backend")
        os.makedirs(backend_dir, exist_ok=True)
        with open(os.path.join(backend_dir, "package.json"), "w", encoding="utf-8") as f:
            f.write("""{
  "name": "backend",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "dev": "node server.js",
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.19.0",
    "cors": "^2.8.5"
  }
}
""")
        with open(os.path.join(backend_dir, "server.js"), "w", encoding="utf-8") as f:
            f.write("""const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/health", (req, res) => {
  res.json({ ok: true, service: "backend", stack: "react-node" });
});

const port = process.env.PORT || 4000;
app.listen(port, () => {
  console.log("Backend listening on port", port);
});
""")

        frontend_dir = os.path.join(base, "frontend")
        os.makedirs(frontend_dir, exist_ok=True)
        with open(os.path.join(frontend_dir, "package.json"), "w", encoding="utf-8") as f:
            f.write("""{
  "name": "frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""")
        os.makedirs(os.path.join(frontend_dir, "src"), exist_ok=True)
        with open(os.path.join(frontend_dir, "index.html"), "w", encoding="utf-8") as f:
            f.write("""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>React Frontend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""")
        with open(os.path.join(frontend_dir, "src", "main.jsx"), "w", encoding="utf-8") as f:
            f.write("""import React from "react";
import ReactDOM from "react-dom/client";

function App() {
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>React + Node App</h1>
      <p>Generated by Boardwalk AI.</p>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
""")

    elif stack == "react-fastapi":
        backend_dir = os.path.join(base, "backend")
        os.makedirs(backend_dir, exist_ok=True)
        with open(os.path.join(backend_dir, "main.py"), "w", encoding="utf-8") as f:
            f.write("""from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
def health():
    return {"ok": True, "service": "backend", "stack": "react-fastapi"}
""")
        with open(os.path.join(backend_dir, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write("fastapi\nuvicorn[standard]\n")

        frontend_dir = os.path.join(base, "frontend")
        os.makedirs(frontend_dir, exist_ok=True)
        with open(os.path.join(frontend_dir, "package.json"), "w", encoding="utf-8") as f:
            f.write("""{
  "name": "frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""")
        os.makedirs(os.path.join(frontend_dir, "src"), exist_ok=True)
        with open(os.path.join(frontend_dir, "index.html"), "w", encoding="utf-8") as f:
            f.write("""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>React + FastAPI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""")
        with open(os.path.join(frontend_dir, "src", "main.jsx"), "w", encoding="utf-8") as f:
            f.write("""import React from "react";
import ReactDOM from "react-dom/client";

function App() {
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>React + FastAPI App</h1>
      <p>Generated by Boardwalk AI.</p>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
""")

    elif stack == "svelte-worker":
        worker_dir = os.path.join(base, "backend-worker")
        os.makedirs(worker_dir, exist_ok=True)
        with open(os.path.join(worker_dir, "worker.js"), "w", encoding="utf-8") as f:
            f.write("""export default {
  async fetch(request, env, ctx) {
    return new Response("Hello from Cloudflare Worker backend (svelte-worker stack)", {
      status: 200,
      headers: { "content-type": "text/plain" }
    });
  }
};
""")
        with open(os.path.join(worker_dir, "wrangler.toml"), "w", encoding="utf-8") as f:
            f.write(f"""name = "{sname}-worker"
main = "worker.js"
compatibility_date = "2024-04-08"
""")

        frontend_dir = os.path.join(base, "frontend-svelte")
        os.makedirs(frontend_dir, exist_ok=True)
        with open(os.path.join(frontend_dir, "package.json"), "w", encoding="utf-8") as f:
            f.write("""{
  "name": "frontend-svelte",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^3.0.0",
    "svelte": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""")
        os.makedirs(os.path.join(frontend_dir, "src"), exist_ok=True)
        with open(os.path.join(frontend_dir, "index.html"), "w", encoding="utf-8") as f:
            f.write("""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Svelte + Worker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
""")
        with open(os.path.join(frontend_dir, "src", "main.js"), "w", encoding="utf-8") as f:
            f.write("""import App from "./App.svelte";

const app = new App({
  target: document.getElementById("app")
});

export default app;
""")
        with open(os.path.join(frontend_dir, "src", "App.svelte"), "w", encoding="utf-8") as f:
            f.write("""<main style="padding:24px;font-family:system-ui;">
  <h1>Svelte + Cloudflare Worker</h1>
  <p>Generated by Boardwalk AI.</p>
</main>
""")

    else:
        raise ValueError(f"Unknown stack '{stack}'")

    return base

# ---------- DB SCHEMA ----------
def create_db_schema(name: str, schema: str) -> str:
    sname = safe_name(name)
    db_dir = os.path.join(FILES_DIR, "db")
    os.makedirs(db_dir, exist_ok=True)
    path = os.path.join(db_dir, f"{sname}.sql")
    with open(path, "w", encoding="utf-8") as f:
        f.write(schema)
    return path

# ---------- R2 CONFIG ----------
def create_r2_config(bucket_name: str) -> str:
    sname = safe_name(bucket_name)
    cf_dir = os.path.join(FILES_DIR, "cloudflare")
    os.makedirs(cf_dir, exist_ok=True)
    path = os.path.join(cf_dir, "r2.toml")
    config = f"""[[r2_buckets]]
binding = "{sname}"
bucket_name = "{sname}"
preview_bucket_name = "{sname}-preview"
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(config)
    return path

# ---------- API BACKEND ----------
def generate_api_backend(project: str, spec: str) -> str:
    sproj = safe_name(project)
    base = os.path.join(FILES_DIR, sproj, "backend")
    os.makedirs(base, exist_ok=True)

    spec_path = os.path.join(base, "api_spec.md")
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(f"# API Spec for {sproj}\n\n{spec}\n")

    server_path = os.path.join(base, "server.js")
    with open(server_path, "w", encoding="utf-8") as f:
        f.write(f"""const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());

// API generated from spec file: api_spec.md
// Project: {sproj}

app.get("/api/health", (req, res) => {{
  res.json({{ ok: true, service: "{sproj}" }});
}});

// TODO: Implement routes described in api_spec.md

const port = process.env.PORT || 4000;
app.listen(port, () => {{
  console.log("API backend for {sproj} listening on port", port);
}});
""")
    return base

# ---------- ENDPOINTS ----------
@app.post("/api/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    last = req.messages[-1].content if req.messages else ""
    reply = f"Note recorded: {last}"
    return ChatResponse(reply=reply)

@app.post("/api/scaffold", response_model=ScaffoldResponse)
def api_scaffold(req: ScaffoldRequest):
    path = scaffold_project(req.stack, req.name)
    return ScaffoldResponse(message=f"Project scaffolded with stack '{req.stack}'", path=path)

@app.post("/api/db/schema", response_model=DbSchemaResponse)
def api_db_schema(req: DbSchemaRequest):
    path = create_db_schema(req.name, req.schema)
    return DbSchemaResponse(message="Database schema file created", path=path)

@app.post("/api/cloudflare/r2", response_model=R2Response)
def api_r2(req: R2Request):
    path = create_r2_config(req.bucket_name)
    return R2Response(message="Cloudflare R2 config created", path=path)

@app.post("/api/api/generate", response_model=ApiGenResponse)
def api_generate(req: ApiGenRequest):
    path = generate_api_backend(req.project, req.spec)
    return ApiGenResponse(message="API backend generated", path=path)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
